# Generated by Django 5.2.5 on 2025-08-06 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duração da partida em minutos', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'matches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.CharField(choices=[('A', 'Time A'), ('B', 'Time B')], max_length=1)),
                ('is_winner', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(help_text='Ordem de jogada')),
                ('points', models.PositiveIntegerField(default=0, help_text='Pontos do jogador na partida')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador da Partida',
                'verbose_name_plural': 'Jogadores da Partida',
                'db_table': 'match_players',
                'ordering': ['position'],
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.PositiveIntegerField(help_text='Número do turno')),
                ('move_type', models.CharField(choices=[('normal', 'Jogada Normal'), ('falta', 'Falta'), ('snooker', 'Snooker'), ('mata_8', 'Mata Bola 8'), ('erro', 'Erro'), ('na_sorte', 'Na Sorte'), ('tabela', 'Tabela'), ('combo', 'Combo'), ('perfect', 'Jogada Perfeita')], max_length=30)),
                ('points', models.IntegerField(default=0, help_text='Pontos ganhos/perdidos na jogada')),
                ('description', models.TextField(blank=True, help_text='Descrição da jogada')),
                ('is_winning_move', models.BooleanField(default=False, help_text='Se foi a jogada que venceu a partida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balls_potted', models.PositiveIntegerField(default=0, help_text='Bolas encaçapadas')),
                ('consecutive_count', models.PositiveIntegerField(default=0, help_text='Contador de jogadas consecutivas')),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, help_text='Tempo gasto na jogada', null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='matches.matchplayer')),
            ],
            options={
                'verbose_name': 'Jogada',
                'verbose_name_plural': 'Jogadas',
                'db_table': 'moves',
                'ordering': ['turn_number', 'created_at'],
            },
        ),
    ]
