# Generated by Django 5.2.5 on 2025-08-06 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código único da conquista', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nome da conquista', max_length=100)),
                ('description', models.TextField(help_text='Descrição da conquista')),
                ('icon_url', models.URLField(blank=True, help_text='URL do ícone da conquista', null=True)),
                ('category', models.CharField(choices=[('habilidade', 'Habilidade'), ('sorte', 'Sorte'), ('estatistica', 'Estatística'), ('estrategia', 'Estratégia'), ('tempo', 'Tempo'), ('diversao', 'Diversão'), ('persistencia', 'Persistência')], help_text='Categoria da conquista', max_length=50)),
                ('points', models.PositiveIntegerField(default=10, help_text='Pontos que a conquista vale')),
                ('is_active', models.BooleanField(default=True, help_text='Se a conquista está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'db_table': 'achievements',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement')),
                ('match', models.ForeignKey(blank=True, help_text='Partida onde a conquista foi desbloqueada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'db_table': 'user_achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
