# Generated by Django 5.2.5 on 2025-08-06 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do campeonato', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição do campeonato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(default=8, help_text='Máximo de participantes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_championships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'db_table': 'championships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(help_text='Número da rodada')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_matches', to='championships.championship')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_matches', to='matches.match')),
            ],
            options={
                'verbose_name': 'Partida do Campeonato',
                'verbose_name_plural': 'Partidas do Campeonato',
                'db_table': 'championship_matches',
                'ordering': ['round_number', 'match__started_at'],
                'unique_together': {('championship', 'match')},
            },
        ),
        migrations.CreateModel(
            name='ChampionshipParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('final_position', models.PositiveIntegerField(blank=True, help_text='Posição final no campeonato', null=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='championships.championship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante do Campeonato',
                'verbose_name_plural': 'Participantes do Campeonato',
                'db_table': 'championship_participants',
                'ordering': ['final_position', 'joined_at'],
                'unique_together': {('championship', 'user')},
            },
        ),
    ]
